server:
  #rootPath: /api/*
  #applicationContextPath: /
  #adminContextPath: /
  applicationConnectors:
    - type: http
      port: 3828
  adminConnectors:
    - type: http
      port: 3829

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: var/log/myapplication.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: var/log/myapplication-%d.log
      archivedFileCount: 5
      timeZone: UTC

atlasdb:
  keyValueService:
    type: cassandra
    servers:
      - 127.0.0.1:9160
      - 127.0.0.2:9160
      - 127.0.0.3:9160
    poolSize: 20
    credentials:
      username: cassandra
      password: cassandra
    ssl: false
    replicationFactor: 1
    mutationBatchCount: 10000
    mutationBatchSizeBytes: 10000000
    fetchBatchCount: 1000
    autoRefreshNodes: false
    ignoreNodeTopologyChecks: true
    ignoreInconsistentRingChecks: true
    ignoreDatacenterConfigurationChecks: true
    ignorePartitionerChecks: true
  initializeAsync: true
  enableSweep: false

  namespace: atlasete

#  leader:
#    quorumSize: 1
#    learnerLogDir: var/data/paxosLog/learner1
#    acceptorLogDir: var/data/paxosLog/acceptor1
#    localServer: http://ete1:3828
#    leaders:
#      - http://ete1:3828
