server:
  #rootPath: /api/*
  #applicationContextPath: /
  #adminContextPath: /
  applicationConnectors:
    - type: http
      port: 3828
  adminConnectors:
    - type: http
      port: 3829

atlasdb:
  keyValueService:
    type: memory

  leader:
    quorumSize: 2
    learnerLogDir: var/data/paxosLog/learner1
    acceptorLogDir: var/data/paxosLog/acceptor1
    localServer: http://ete1:3828
    leaders:
      - http://ete1:3828
      - http://ete2:3828
      - http://ete3:3828
